### ISSUE TITLE
IllegalAccessError with recent Ebean

### ISSUE THREAD

**Issue by zsoltm** [ebean-orm/ebean-spring-txn#20]
I'm getting an IllegalAccessError with the most recent release of this package (11.10.4) paired with eBean 11.41.1.

It seems this package uses quite an old eBean (11.10.3), I believe there is a breaking change introduced in eBean since then. Indeed `notifyOfCommit(SpiTransaction)` is package private now in `TransactionManager`.

Stack trace:

```
java.lang.IllegalAccessError: tried to access method io.ebeaninternal.server.transaction.TransactionManager.notifyOfCommit(Lio/ebeaninternal/api/SpiTransaction;)V from class io.ebean.spring.txn.SpringJdbcTransactionManager$SpringTxnListener
	at io.ebean.spring.txn.SpringJdbcTransactionManager$SpringTxnListener.afterCompletion(SpringJdbcTransactionManager.java:177) ~[ebean-spring-txn-11.10.4.jar:na]
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCompletion(TransactionSynchronizationUtils.java:171) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.invokeAfterCompletion(AbstractPlatformTransactionManager.java:992) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCompletion(AbstractPlatformTransactionManager.java:967) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:788) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:533) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) [spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at my.app.class.that.is.annotated.with.Transactional$$EnhancerBySpringCGLIB$$81daac54.createNew(<generated>) [classes/:na] *** edited
```

**Comment by rbygrave** [comment]
> paired with eBean 11.41.1

That's correct.  You need to bump Ebean to 11.42.1

**Comment by zsoltm** [comment]
@rbygrave thank you for the quick feedback. Indeed this solves the issue.

I noticed that 11.42.x rolled out since, but after a quick scan through the changelog I missed the relevant change, my bad.

**Comment by rbygrave** [comment]
No worries - glad that has sorted it.  It was may stuff up in the first place that caused this :)
