### ISSUE TITLE
NoSuchMethodError: 'void io.ebeaninternal.server.transaction.ExternalJdbcTransaction.<init>(java.lang.String, boolean, java.sql.Connection, io.ebeaninternal.server.transaction.TransactionManager)'

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-spring-txn#34]
Ebean 13.13.0 introduced a change that makes it incompatible with ebean-spring-txn 13.10.0.

This fixes this issue.

```
Caused by: java.lang.NoSuchMethodError: 'void io.ebeaninternal.server.transaction.ExternalJdbcTransaction.<init>(java.lang.String, boolean, java.sql.Connection, io.ebeaninternal.server.transaction.TransactionManager)'
	at io.ebean.spring.txn.SpringJdbcTransaction.<init>(SpringJdbcTransaction.java:12)
	at io.ebean.spring.txn.SpringJdbcTransactionManager.getCurrentTransaction(SpringJdbcTransactionManager.java:76)
	at io.ebeaninternal.server.transaction.ExternalTransactionScopeManager.active(ExternalTransactionScopeManager.java:27)
	at io.ebeaninternal.server.transaction.TransactionManager.active(TransactionManager.java:176)
	at io.ebeaninternal.server.core.DefaultServer.currentServerTransaction(DefaultServer.java:727)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1073)
```

**Comment by rbygrave** [comment]
Fixed by https://github.com/ebean-orm/ebean-spring-txn/commit/a9575048b4429a0bd8f759ed436ce39f2a9e97e5
